<?php

namespace Database\Seeders;

use Database\Factories\EventFactory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Event::truncate();

        Event::create([
            'judul_event' => 'Lomba Kebudayaan Menyambut Kebangkitan Budaya Kabupaten Lahat',
            'deskripsi' => '<p>Kabupaten Lahat, sebuah daerah yang kaya akan budaya dan tradisi, akan segera menyelenggarakan Lomba Kebudayaan yang menarik dan meriah. Dalam upaya untuk memperkuat identitas budaya lokal, Dinas Pendidikan dan Kebudayaan Kabupaten Lahat telah mengumumkan rencana untuk mengadakan lomba kebudayaan yang akan datang. Acara ini diharapkan menjadi wahana yang luar biasa bagi masyarakat Lahat untuk merayakan kekayaan budaya mereka dan meningkatkan apresiasi terhadap warisan lokal.</p><p>Lomba Kebudayaan ini dijadwalkan akan berlangsung dalam waktu dekat, yang bertujuan untuk memperkenalkan dan mempromosikan beragam aspek budaya Kabupaten Lahat kepada generasi muda dan masyarakat umum. Selain itu, kegiatan ini juga diharapkan dapat menginspirasi generasi muda untuk melestarikan tradisi dan memperkaya kehidupan budaya setempat.</p><p>Berikut adalah beberapa informasi tentang Lomba Kebudayaan yang akan datang:</p><p><span style="color: var(--tw-prose-bold);">Tanggal dan Tempat</span></p><p>Lomba Kebudayaan ini akan diadakan pada tanggal [tanggal] di [lokasi]. Lokasi tersebut telah dipilih dengan cermat agar dapat menampung semua peserta dan penonton dengan nyaman.</p><p><span style="color: var(--tw-prose-bold);">Kategori Lomba</span></p><p>Lomba Kebudayaan akan terdiri dari berbagai kategori, di antaranya:</p><ol><li>Tarian Tradisional: Peserta akan menampilkan tarian tradisional yang menggambarkan keindahan gerakan dan kekayaan budaya Kabupaten Lahat.</li><li>Musik Tradisional: Peserta akan memainkan alat musik tradisional dan menyajikan musik yang khas dari daerah mereka.</li><li>Busana Tradisional: Peserta akan berkompetisi dengan mengenakan busana tradisional yang mencerminkan keunikan dan keindahan warisan budaya Kabupaten Lahat.</li><li>Kuliner Tradisional: Peserta akan memperkenalkan hidangan tradisional yang menggugah selera dari Kabupaten Lahat.</li></ol><p><span style="color: var(--tw-prose-bold);">Syarat dan Ketentuan</span></p><p>Untuk dapat berpartisipasi dalam Lomba Kebudayaan, peserta diharapkan memenuhi beberapa syarat dan ketentuan tertentu yang ditetapkan oleh panitia. Informasi lebih lanjut mengenai persyaratan dan prosedur pendaftaran dapat ditemukan di situs web resmi Dinas Pendidikan dan Kebudayaan Kabupaten Lahat atau menghubungi panitia penyelenggara melalui kontak yang tersedia.</p><p><span style="color: var(--tw-prose-bold);">Manfaat dan Tujuan</span></p><p>Lomba Kebudayaan ini bertujuan untuk mendorong pemeliharaan dan pengembangan kekayaan budaya Kabupaten Lahat. Acara ini akan memberikan manfaat yang berkelanjutan, termasuk:</p><ol><li>Peningkatan kesadaran dan apresiasi masyarakat terhadap kebudayaan lokal.</li><li>Pengenalan generasi muda terhadap warisan budaya mereka dan membangun rasa kebanggaan akan identitas budaya.</li><li>Peningkatan partisipasi</li></ol><p><br></p>',
            'tempat' => 'Lapangan Seganti Setungguan Ex. MTQ',
            'tanggal_mulai' => '2023-04-15 10:00:00',
            'tanggal_selesai' => '2023-06-29 00:00:00',
            'thumbnail' => 'default.png',
            'kategori' => 'Festival',
        ]);

        Event::create([
            'judul_event' => 'Menghidupkan Tradisi Pernikahan Adat di Kabupaten Lahat: Lomba Adat Pengantin Terbaik',
            'deskripsi' => '<p>Kabupaten Lahat, sebuah daerah yang kaya akan budaya dan tradisi, sedang bersiap-siap untuk merayakan keindahan dan keunikan pernikahan adat. Dalam upaya untuk mempertahankan dan mempromosikan kearifan lokal, Dinas Pendidikan dan Kebudayaan Kabupaten Lahat telah mengumumkan rencana untuk mengadakan Lomba Adat Pengantin Terbaik, sebuah acara yang akan menghidupkan tradisi pernikahan adat di tengah-tengah masyarakat.</p><p>Lomba Adat Pengantin Terbaik ini akan menjadi kesempatan bagi masyarakat Kabupaten Lahat untuk mempelajari, menghargai, dan menghidupkan kembali tradisi pernikahan adat yang khas. Acara ini diharapkan dapat memperkuat ikatan sosial, menghormati leluhur, serta mewujudkan nilai-nilai budaya yang diwariskan dari generasi ke generasi.</p><p>Berikut adalah beberapa informasi penting tentang Lomba Adat Pengantin Terbaik:</p><p><span style="color: var(--tw-prose-bold);">Tujuan Lomba</span></p><p>Lomba Adat Pengantin Terbaik bertujuan untuk:</p><ol><li>Memperkenalkan dan mempromosikan kekayaan tradisi pernikahan adat di Kabupaten Lahat.</li><li>Mempertahankan dan melestarikan warisan budaya lokal.</li><li>Meningkatkan apresiasi masyarakat terhadap keindahan dan keunikan pernikahan adat.</li><li>Mendorong partisipasi aktif masyarakat dalam menjaga dan menghidupkan tradisi pernikahan adat.</li></ol><p><span style="color: var(--tw-prose-bold);">Tanggal dan Tempat</span></p><p>Lomba Adat Pengantin Terbaik ini akan dilaksanakan pada tanggal [tanggal] di [lokasi]. Tempat yang dipilih telah disesuaikan agar dapat menampung peserta, penonton, dan komite juri dengan nyaman.</p><p><span style="color: var(--tw-prose-bold);">Kategori Lomba</span></p><p>Lomba Adat Pengantin Terbaik akan terdiri dari beberapa kategori, di antaranya:</p><ol><li>Busana Pengantin: Peserta akan menampilkan busana adat pengantin yang mencerminkan keindahan, keunikan, dan kekayaan budaya Kabupaten Lahat.</li><li>Riasan dan Aksesoris: Peserta akan ditantang untuk menghias dan merias diri dengan menggunakan riasan dan aksesoris yang sesuai dengan tradisi pernikahan adat.</li><li>Upacara Adat: Peserta akan memperagakan upacara pernikahan adat yang melibatkan berbagai elemen seperti tarian, nyanyian, dan ritual tertentu.</li><li>Tatanan Rambut: Peserta akan menampilkan beragam tatanan rambut adat yang melengkapi penampilan pengantin.</li></ol><p><span style="color: var(--tw-prose-bold);">Syarat dan Ketentuan</span></p><p>Peserta Lomba Adat Pengantin Terbaik diharapkan memenuhi beberapa syarat dan ketentuan yang ditetapkan oleh panitia. Informasi lengkap mengenai persyaratan pendaftaran, tata cara pelaksanaan, dan batas waktu pendaftaran dapat ditemukan di situs web resmi Dinas Pendidikan dan Kebudayaan Kabupaten</p>',
            'tempat' => 'Gedung Kesenian Kabupaten Lahat',
            'tanggal_mulai' => '2023-06-27 00:00:00',
            'tanggal_selesai' => '2023-06-28 00:00:00',
            'thumbnail' => 'default.png',
            'kategori' => 'Festival',
        ]);

        Event::create([
            'judul_event' => 'Festival Seni dan Budaya "Mandiri Kreatif" Kabupaten Lahat: Menciptakan Keajaiban Budaya dalam Kreasi Modern',
            'deskripsi' => '<p>Kabupaten Lahat, sebuah daerah yang kaya akan seni dan budaya, akan segera menjadi tuan rumah Festival Seni dan Budaya "Mandiri Kreatif". Acara yang ditunggu-tunggu ini, yang diselenggarakan oleh Dinas Pendidikan dan Kebudayaan Kabupaten Lahat, akan menghadirkan kombinasi menakjubkan antara tradisi dan kreativitas modern, menghasilkan keajaiban budaya yang tak terlupakan.</p><p>Festival Seni dan Budaya "Mandiri Kreatif" bertujuan untuk memperkenalkan dan mempromosikan kekayaan budaya Kabupaten Lahat kepada masyarakat lokal dan pengunjung dari luar daerah. Acara ini juga menginspirasi dan mendorong para seniman, kreatif, dan pelaku budaya untuk berinovasi dalam menggabungkan unsur-unsur tradisional dengan bentuk ekspresi modern.</p><p>Berikut adalah beberapa informasi tentang Festival Seni dan Budaya "Mandiri Kreatif":</p><p><span style="color: var(--tw-prose-bold);">Tanggal dan Tempat</span></p><p>Festival ini akan diadakan pada tanggal [tanggal] di [lokasi]. Tempat tersebut telah dipilih dengan cermat agar dapat menampung berbagai pertunjukan seni dan aktivitas kreatif dengan nyaman.</p><p><span style="color: var(--tw-prose-bold);">Program Acara</span></p><p>Festival Seni dan Budaya "Mandiri Kreatif" akan menampilkan beragam program yang mencakup:</p><ol><li>Pertunjukan Seni Panggung: Pertunjukan seni teater, tari, musik, dan drama yang menggabungkan unsur-unsur tradisional dengan kreativitas modern.</li><li>Pameran Seni: Pameran karya seni visual seperti lukisan, patung, instalasi seni, dan kerajinan tangan yang memperlihatkan keindahan dan kekayaan budaya lokal.</li><li>Workshop dan Demonstrasi: Serangkaian workshop dan demonstrasi yang melibatkan para seniman dan pengrajin lokal, memungkinkan masyarakat untuk belajar langsung tentang teknik dan keterampilan seni tradisional.</li><li>Kompetisi Seni: Kompetisi seni untuk kategori-kategori seperti lukisan, fotografi, seni digital, dan lainnya, yang memungkinkan para seniman lokal untuk berkompetisi dan memperlihatkan bakat mereka.</li><li>Pesta Rakyat: Acara ini juga akan menyajikan pesta rakyat dengan makanan, kios kerajinan, dan pertunjukan kebudayaan rakyat yang memperkuat kebersamaan dan kegembiraan dalam merayakan warisan budaya.</li></ol><p><span style="color: var(--tw-prose-bold);">Tujuan Festival</span></p><p>Festival Seni dan Budaya "Mandiri Kreatif" memiliki beberapa tujuan utama, antara lain:</p><ol><li>Mempromosikan dan melestarikan warisan budaya Kabupaten Lahat kepada generasi muda dan masyarakat umum.</li><li>Mendorong kolaborasi dan inovasi dalam menciptakan karya seni dan produk kreatif yang menggabungkan tradisi dengan tren modern.</li><li>Memberikan platform bagi seniman, kreatif, dan pelaku budaya lokal untuk memamerkan karya mereka</li></ol><p><br></p>',
            'tempat' => 'Gedung Kesenian Kabupaten Lahat',
            'tanggal_mulai' => '2023-06-27 00:00:00',
            'tanggal_selesai' => '2023-06-28 00:00:00',
            'thumbnail' => 'default.png',
            'kategori' => 'Festival',
        ]);

        Event::create([
            'judul_event' => 'Semarakkan Wisata Alam Kabupaten Lahat: Festival Ekowisata "Alam Indah"',
            'deskripsi' => '<p>Kabupaten Lahat, yang dikenal dengan keindahan alamnya yang memukau, akan segera menggelar Festival Ekowisata "Alam Indah". Festival ini merupakan upaya dari Dinas Pariwisata dan Lingkungan Hidup Kabupaten Lahat untuk mempromosikan potensi ekowisata yang luar biasa di daerah ini dan meningkatkan kesadaran masyarakat akan pentingnya pelestarian lingkungan.</p><p>Festival Ekowisata "Alam Indah" akan menawarkan pengalaman tak terlupakan kepada pengunjung, dengan menggabungkan kegiatan edukatif, kegiatan alam terbuka, dan kegiatan kebudayaan. Acara ini diharapkan dapat meningkatkan apresiasi terhadap keindahan alam Kabupaten Lahat serta mempromosikan praktek ekowisata yang bertanggung jawab.</p><p>Berikut adalah beberapa informasi tentang Festival Ekowisata "Alam Indah":</p><p><span style="color: var(--tw-prose-bold);">Tanggal dan Tempat</span></p><p>Festival ini akan berlangsung selama beberapa hari pada tanggal [tanggal] di berbagai lokasi alam yang menakjubkan di Kabupaten Lahat. Setiap lokasi telah dipilih dengan cermat untuk menawarkan pengalaman ekowisata yang unik.</p><p><span style="color: var(--tw-prose-bold);">Program Acara</span></p><p>Festival Ekowisata "Alam Indah" akan menampilkan berbagai kegiatan yang mencakup:</p><ol><li>Petualangan Alam: Kegiatan seperti hiking, trekking, dan camping di beberapa objek wisata alam terkenal di Kabupaten Lahat, seperti Gunung Dempo, Danau Ranau, dan Air Terjun Lematang.</li><li>Pendidikan Lingkungan: Sesi edukatif yang melibatkan masyarakat, khususnya anak-anak dan remaja, untuk meningkatkan kesadaran tentang pentingnya pelestarian lingkungan dan konservasi sumber daya alam.</li><li>Kegiatan Kreatif: Workshop seni dan kerajinan tangan menggunakan bahan alami serta kegiatan fotografi alam untuk memotret keindahan alam Kabupaten Lahat.</li><li>Pertunjukan Budaya: Pertunjukan seni dan budaya tradisional yang memperlihatkan kekayaan warisan budaya lokal, termasuk tarian tradisional, musik, dan pementasan teater.</li><li>Pameran dan Pasar Ekowisata: Pameran yang menampilkan produk-produk ekowisata lokal, seperti kerajinan tangan, makanan organik, produk ramah lingkungan, dan lainnya.</li></ol><p><span style="color: var(--tw-prose-bold);">Tujuan Festival</span></p><p>Festival Ekowisata "Alam Indah" memiliki beberapa tujuan, di antaranya:</p><ol><li>Mempromosikan pariwisata alam Kabupaten Lahat dan menarik wisatawan untuk mengunjungi destinasi ekowisata yang menakjubkan di daerah ini.</li><li>Meningkatkan kesadaran masyarakat akan pentingnya menjaga dan melestarikan alam serta lingkungan hidup.</li><li>Memberikan platform bagi pelaku ekowisata lokal untuk memperkenalkan produk-produk dan jasa-jasa mereka kepada pengunjung dan wisatawan.</li><li>Mendorong partisipasi masyarakat dalam kegiatan ek</li></ol><p><br></p>',
            'tempat' => 'Kabupaten Lahat',
            'tanggal_mulai' => '2023-06-27 00:00:00',
            'tanggal_selesai' => '2023-06-28 00:00:00',
            'thumbnail' => 'default.png',
            'kategori' => 'Festival',
        ]);

        // Event::factory()->count(10)->create();
    }
}
